### ISSUE TITLE
input-event-struct won't serialize correctly with 32 bit unix time

### ISSUE THREAD

**Issue by olewhalehunter** [jtgans/cl-evdev#2]
binary-types of tv_sec and tv_usec in input-event-struct in evdev.lisp need to handle 32/64 bit environment case

see #1

**Comment by jtgans** [comment]
Nice catch. The original use case for cl-evdev was actually on a 32-bit system, which is why I missed this bit. Really, I'd like to see about adjusting the library to instead use grovel, in which case this won't be an issue anymore.
